// SEARCH ARTIST

export const SEARCH_ARTIST_REQUEST = 'SEARCH_ARTIST_REQUEST';
export const SEARCH_ARTIST_SUCCESS = 'SEARCH_ARTIST_SUCCESS';
export const SEARCH_ARTIST_FAILED = 'SEARCH_ARTIST_FAILED';