// SEARCH ARTIST

export const SEARCH_ARTIST_REQUEST = 'SEARCH_ARTIST_REQUEST';
export const SEARCH_ARTIST_SUCCESS = 'SEARCH_ARTIST_SUCCESS';
export const SEARCH_ARTIST_FAILED = 'SEARCH_ARTIST_FAILED';

// SEARCH SONG

export const SEARCH_SONG_REQUEST = 'SEARCH_SONG_REQUEST';
export const SEARCH_SONG_SUCCESS = 'SEARCH_SONG_SUCCESS';
export const SEARCH_SONG_FAILED = 'SEARCH_SONG_FAILED';

// AUTHTOKEN
export const AUTH_TOKEN = 'SEARCH_SONG_REQUEST';
